export const BETTING_RECORD_ACTION = 'bettingRecord.action'
export const BETTING_RECORD_MUTATION = 'bettingRecord.mutation'
export const CURRENT_RECORD_ACTION = 'currentRecord.action'
export const CURRENT_RECORD_MUTATION = 'currentRecord.mutation'
export const GETPLATFORM_RECORD_ACTION = 'getPlatform.action'
export const GET_BETTING_RECORD_ACTION = 'getBetingRecord.action'
export const GET_GETGAMETYPE_RECORD_ACTION = 'getGameType'
