export const AWARD_OPENAWARD = 'award.action'
export const AWARD_OPENAWARD_DETAIL = 'award.awardDetail'
export const AWARD_OPENAWARD_LAST10 = 'awardLast10.action'
export const AWARD_OPENAWARD_LAST10_DETAIL = 'awardLast10.awardDetail'
export const AWARD_LOTTERY_MUTATION_INITDETAIL = 'award.lottery.mutation.action'
export const AWARD_LOTTERY_ACTION = 'award.lottery.action'
