export const BET_ODDS = 'betOdds.action'
export const BET_ODDS_DETAIL = 'betOddsDetail.action'
export const MMC_BETTING_ACTION = 'mmcBetting.action' // 秒秒彩投注
export const MMC_BETTING_MUTATION = 'mmcBetting.mutation'
export const SIMULATE_ACTION = 'simulate.action'
export const SIMULATE_MUTATION = 'simulate.mutation'
export const BETTING_GET_PERIODNO = 'bettingGetPeriodNo.mutation'
export const BETTING_GET_BETTING_STATES = 'getBettingStates.mutation'
export const BETTING_ACTION = 'betting.action' // 通用彩票投注
export const GETPERIOD_LIST_MUTATION = 'getPeriodList.mutation'
export const FFC_PERIOD_LIST_MUTATION = 'ffcPeriodList.mutation'
export const CHECK_LOGIN_TOKEN_ACTION = 'checkLoginToken.action' // 校验登录状态
export const CHECK_LOGIN_TOKEN_MUTATION = 'checkLoginToken.mutation'
export const CURRENT_ZODIAC_ACTION = 'currentZodiac.action' // 获取当年生肖
export const CURRENT_ZODIAC_MUTATION = 'currentZodiac.mutation'
// export const GET_LOTTERY_TIMES_ACTION = 'getLotteryTimes.action' // 获取彩票倒计时
// export const GET_LOTTERY_TIMES_MUTATION = 'getLotteryTimes.mutation'
export const PERIOD_ACTION = 'period.action' // 获取期数
// export const PERIOD_MUTATION = 'period.mutation' // 获取期数
export const GET_LOTTERY_STATES_ACTION = 'getLotteryStates.action' // 获取彩票状态
export const GET_LOTTERY_STATES_MUTATION = 'getLotteryStates.mutation' // 获取彩票状态
export const GET_GAME_STATUS_ACTION = 'getGameStatus.action' // 获取秒秒彩游戏状态
export const GET_GAME_STATUS_MUTATION = 'getGameStatus.mutation' // 获取秒秒彩游戏状态
export const TODAY_SIMULATE_RESULT_ACTION = 'todaySimulateResult.action' // 秒秒彩种，当前用户今日模拟开奖数据
export const TODAY_SIMULATE_RESULT_MUTATION = 'todaySimulateResult.mutation'
